fixtures:
  repositories:
    stdlib:     'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    extlib:     'https://github.com/voxpupuli/puppet-extlib'
    certs:      'https://github.com/theforeman/puppet-certs'
    concat:     'https://github.com/puppetlabs/puppetlabs-concat'
    postgresql: 'https://github.com/puppetlabs/puppetlabs-postgresql.git'
    selinux_core:
      repo:           'https://github.com/puppetlabs/puppetlabs-selinux_core'
      puppet_version: '>= 6.0.0'
    yumrepo_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core'
      puppet_version: '>= 6.0.0'
