---
.puppet-lint.rc:
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
.github/workflows/ci.yml:
  beaker_facter: 'candlepin_baseurl:Candlepin:https://stagingyum.theforeman.org/candlepin/4.4/el9/x86_64/,https://stagingyum.theforeman.org/candlepin/4.4/el8/x86_64/'
