name        	'katello-candlepin'
version     	'0.1.0'
source      	'https://github.com/Katello/puppet-candlepin.git'
author      	'Katello'
license	    	'GPLv3+'
summary     	'Configure and install a Candlepin entitlement server.'
description    	'Configure and install a Candlepin entitlement server.'
project_page   	'https://github.com/Katello/puppet-candlepin'

dependency 'puppetlabs/stdlib', '>= 4.2.0'
dependency 'puppetlabs/postgresql', '>= 3.0.0'
dependency 'theforeman/foreman', '>= 1.5.0'
dependency 'theforeman/concat_native', '>= 1.3.0'
