---
name: CI

on:
  pull_request:


concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  puppet:
    name: Puppet
    uses: voxpupuli/gha-puppet/.github/workflows/beaker.yml@v2
    with:
      pidfile_workaround: 'false'
      rubocop: false
      cache-version: '1'
      beaker_facter: 'candlepin_baseurl:Candlepin:https://stagingyum.theforeman.org/candlepin/4.4/el9/x86_64/,https://stagingyum.theforeman.org/candlepin/4.4/el8/x86_64/'
